export interface EnglishWord {
  english: string;
  turkish: string;
  level: 1 | 2 | 3; // 1=kolay, 2=orta, 3=zor
}

export const ENGLISH_WORDS: EnglishWord[] = [
  // Seviye 1 — Günlük temel kelimeler
  { english: 'apple', turkish: 'elma', level: 1 },
  { english: 'water', turkish: 'su', level: 1 },
  { english: 'house', turkish: 'ev', level: 1 },
  { english: 'cat', turkish: 'kedi', level: 1 },
  { english: 'dog', turkish: 'köpek', level: 1 },
  { english: 'book', turkish: 'kitap', level: 1 },
  { english: 'car', turkish: 'araba', level: 1 },
  { english: 'food', turkish: 'yiyecek', level: 1 },
  { english: 'school', turkish: 'okul', level: 1 },
  { english: 'friend', turkish: 'arkadaş', level: 1 },
  { english: 'family', turkish: 'aile', level: 1 },
  { english: 'mother', turkish: 'anne', level: 1 },
  { english: 'father', turkish: 'baba', level: 1 },
  { english: 'sister', turkish: 'kız kardeş', level: 1 },
  { english: 'brother', turkish: 'erkek kardeş', level: 1 },
  { english: 'child', turkish: 'çocuk', level: 1 },
  { english: 'girl', turkish: 'kız', level: 1 },
  { english: 'boy', turkish: 'erkek çocuk', level: 1 },
  { english: 'man', turkish: 'adam', level: 1 },
  { english: 'woman', turkish: 'kadın', level: 1 },
  { english: 'day', turkish: 'gün', level: 1 },
  { english: 'night', turkish: 'gece', level: 1 },
  { english: 'morning', turkish: 'sabah', level: 1 },
  { english: 'sun', turkish: 'güneş', level: 1 },
  { english: 'moon', turkish: 'ay', level: 1 },
  { english: 'star', turkish: 'yıldız', level: 1 },
  { english: 'sky', turkish: 'gökyüzü', level: 1 },
  { english: 'sea', turkish: 'deniz', level: 1 },
  { english: 'tree', turkish: 'ağaç', level: 1 },
  { english: 'flower', turkish: 'çiçek', level: 1 },
  { english: 'bird', turkish: 'kuş', level: 1 },
  { english: 'fish', turkish: 'balık', level: 1 },
  { english: 'horse', turkish: 'at', level: 1 },
  { english: 'cow', turkish: 'inek', level: 1 },
  { english: 'sheep', turkish: 'koyun', level: 1 },
  { english: 'bread', turkish: 'ekmek', level: 1 },
  { english: 'milk', turkish: 'süt', level: 1 },
  { english: 'egg', turkish: 'yumurta', level: 1 },
  { english: 'meat', turkish: 'et', level: 1 },
  { english: 'rice', turkish: 'pirinç', level: 1 },
  { english: 'tea', turkish: 'çay', level: 1 },
  { english: 'coffee', turkish: 'kahve', level: 1 },
  { english: 'orange', turkish: 'portakal', level: 1 },
  { english: 'banana', turkish: 'muz', level: 1 },
  { english: 'grape', turkish: 'üzüm', level: 1 },
  { english: 'table', turkish: 'masa', level: 1 },
  { english: 'chair', turkish: 'sandalye', level: 1 },
  { english: 'door', turkish: 'kapı', level: 1 },
  { english: 'window', turkish: 'pencere', level: 1 },
  { english: 'bed', turkish: 'yatak', level: 1 },
  { english: 'hand', turkish: 'el', level: 1 },
  { english: 'eye', turkish: 'göz', level: 1 },
  { english: 'ear', turkish: 'kulak', level: 1 },
  { english: 'nose', turkish: 'burun', level: 1 },
  { english: 'mouth', turkish: 'ağız', level: 1 },
  { english: 'head', turkish: 'kafa', level: 1 },
  { english: 'heart', turkish: 'kalp', level: 1 },
  { english: 'foot', turkish: 'ayak', level: 1 },
  { english: 'hair', turkish: 'saç', level: 1 },
  { english: 'face', turkish: 'yüz', level: 1 },
  { english: 'road', turkish: 'yol', level: 1 },
  { english: 'city', turkish: 'şehir', level: 1 },
  { english: 'village', turkish: 'köy', level: 1 },
  { english: 'country', turkish: 'ülke', level: 1 },
  { english: 'world', turkish: 'dünya', level: 1 },
  { english: 'fire', turkish: 'ateş', level: 1 },
  { english: 'rain', turkish: 'yağmur', level: 1 },
  { english: 'snow', turkish: 'kar', level: 1 },
  { english: 'wind', turkish: 'rüzgar', level: 1 },
  { english: 'stone', turkish: 'taş', level: 1 },
  { english: 'name', turkish: 'isim', level: 1 },
  { english: 'word', turkish: 'kelime', level: 1 },
  { english: 'number', turkish: 'sayı', level: 1 },
  { english: 'color', turkish: 'renk', level: 1 },
  { english: 'red', turkish: 'kırmızı', level: 1 },
  { english: 'blue', turkish: 'mavi', level: 1 },
  { english: 'green', turkish: 'yeşil', level: 1 },
  { english: 'white', turkish: 'beyaz', level: 1 },
  { english: 'black', turkish: 'siyah', level: 1 },
  { english: 'yellow', turkish: 'sarı', level: 1 },
  { english: 'big', turkish: 'büyük', level: 1 },
  { english: 'small', turkish: 'küçük', level: 1 },
  { english: 'good', turkish: 'iyi', level: 1 },
  { english: 'bad', turkish: 'kötü', level: 1 },
  { english: 'hot', turkish: 'sıcak', level: 1 },
  { english: 'cold', turkish: 'soğuk', level: 1 },
  { english: 'fast', turkish: 'hızlı', level: 1 },
  { english: 'slow', turkish: 'yavaş', level: 1 },
  { english: 'old', turkish: 'eski/yaşlı', level: 1 },
  { english: 'new', turkish: 'yeni', level: 1 },
  { english: 'long', turkish: 'uzun', level: 1 },
  { english: 'short', turkish: 'kısa', level: 1 },
  { english: 'happy', turkish: 'mutlu', level: 1 },
  { english: 'sad', turkish: 'üzgün', level: 1 },
  { english: 'love', turkish: 'sevgi/aşk', level: 1 },
  { english: 'time', turkish: 'zaman', level: 1 },
  { english: 'year', turkish: 'yıl', level: 1 },
  { english: 'money', turkish: 'para', level: 1 },
  { english: 'life', turkish: 'hayat', level: 1 },
  // Seviye 2 — Orta düzey kelimeler
  { english: 'animal', turkish: 'hayvan', level: 2 },
  { english: 'answer', turkish: 'cevap', level: 2 },
  { english: 'question', turkish: 'soru', level: 2 },
  { english: 'problem', turkish: 'sorun', level: 2 },
  { english: 'story', turkish: 'hikaye', level: 2 },
  { english: 'music', turkish: 'müzik', level: 2 },
  { english: 'game', turkish: 'oyun', level: 2 },
  { english: 'sport', turkish: 'spor', level: 2 },
  { english: 'health', turkish: 'sağlık', level: 2 },
  { english: 'hospital', turkish: 'hastane', level: 2 },
  { english: 'doctor', turkish: 'doktor', level: 2 },
  { english: 'teacher', turkish: 'öğretmen', level: 2 },
  { english: 'student', turkish: 'öğrenci', level: 2 },
  { english: 'office', turkish: 'ofis', level: 2 },
  { english: 'market', turkish: 'market', level: 2 },
  { english: 'price', turkish: 'fiyat', level: 2 },
  { english: 'letter', turkish: 'mektup/harf', level: 2 },
  { english: 'paper', turkish: 'kağıt', level: 2 },
  { english: 'pen', turkish: 'kalem', level: 2 },
  { english: 'picture', turkish: 'resim', level: 2 },
  { english: 'phone', turkish: 'telefon', level: 2 },
  { english: 'computer', turkish: 'bilgisayar', level: 2 },
  { english: 'internet', turkish: 'internet', level: 2 },
  { english: 'message', turkish: 'mesaj', level: 2 },
  { english: 'minute', turkish: 'dakika', level: 2 },
  { english: 'hour', turkish: 'saat', level: 2 },
  { english: 'week', turkish: 'hafta', level: 2 },
  { english: 'month', turkish: 'ay', level: 2 },
  { english: 'evening', turkish: 'akşam', level: 2 },
  { english: 'afternoon', turkish: 'öğleden sonra', level: 2 },
  { english: 'season', turkish: 'mevsim', level: 2 },
  { english: 'spring', turkish: 'ilkbahar', level: 2 },
  { english: 'summer', turkish: 'yaz', level: 2 },
  { english: 'autumn', turkish: 'sonbahar', level: 2 },
  { english: 'winter', turkish: 'kış', level: 2 },
  { english: 'forest', turkish: 'orman', level: 2 },
  { english: 'mountain', turkish: 'dağ', level: 2 },
  { english: 'river', turkish: 'nehir', level: 2 },
  { english: 'island', turkish: 'ada', level: 2 },
  { english: 'bridge', turkish: 'köprü', level: 2 },
  { english: 'garden', turkish: 'bahçe', level: 2 },
  { english: 'street', turkish: 'sokak', level: 2 },
  { english: 'station', turkish: 'istasyon', level: 2 },
  { english: 'airport', turkish: 'havalimanı', level: 2 },
  { english: 'hotel', turkish: 'otel', level: 2 },
  { english: 'restaurant', turkish: 'restoran', level: 2 },
  { english: 'kitchen', turkish: 'mutfak', level: 2 },
  { english: 'bedroom', turkish: 'yatak odası', level: 2 },
  { english: 'bathroom', turkish: 'banyo', level: 2 },
  { english: 'wall', turkish: 'duvar', level: 2 },
  { english: 'floor', turkish: 'zemin', level: 2 },
  { english: 'roof', turkish: 'çatı', level: 2 },
  { english: 'dream', turkish: 'rüya', level: 2 },
  { english: 'idea', turkish: 'fikir', level: 2 },
  { english: 'plan', turkish: 'plan', level: 2 },
  { english: 'hope', turkish: 'umut', level: 2 },
  { english: 'fear', turkish: 'korku', level: 2 },
  { english: 'anger', turkish: 'öfke', level: 2 },
  { english: 'smile', turkish: 'gülümseme', level: 2 },
  { english: 'laugh', turkish: 'gülmek', level: 2 },
  { english: 'cry', turkish: 'ağlamak', level: 2 },
  { english: 'sleep', turkish: 'uyumak', level: 2 },
  { english: 'wake', turkish: 'uyanmak', level: 2 },
  { english: 'walk', turkish: 'yürümek', level: 2 },
  { english: 'run', turkish: 'koşmak', level: 2 },
  { english: 'jump', turkish: 'zıplamak', level: 2 },
  { english: 'swim', turkish: 'yüzmek', level: 2 },
  { english: 'fly', turkish: 'uçmak', level: 2 },
  { english: 'drive', turkish: 'sürmek', level: 2 },
  { english: 'cook', turkish: 'pişirmek', level: 2 },
  { english: 'eat', turkish: 'yemek', level: 2 },
  { english: 'drink', turkish: 'içmek', level: 2 },
  { english: 'write', turkish: 'yazmak', level: 2 },
  { english: 'read', turkish: 'okumak', level: 2 },
  { english: 'speak', turkish: 'konuşmak', level: 2 },
  { english: 'listen', turkish: 'dinlemek', level: 2 },
  { english: 'see', turkish: 'görmek', level: 2 },
  { english: 'hear', turkish: 'duymak', level: 2 },
  { english: 'think', turkish: 'düşünmek', level: 2 },
  { english: 'know', turkish: 'bilmek', level: 2 },
  { english: 'learn', turkish: 'öğrenmek', level: 2 },
  { english: 'teach', turkish: 'öğretmek', level: 2 },
  { english: 'work', turkish: 'çalışmak', level: 2 },
  { english: 'play', turkish: 'oynamak', level: 2 },
  { english: 'win', turkish: 'kazanmak', level: 2 },
  { english: 'lose', turkish: 'kaybetmek', level: 2 },
  { english: 'help', turkish: 'yardım etmek', level: 2 },
  { english: 'give', turkish: 'vermek', level: 2 },
  { english: 'take', turkish: 'almak', level: 2 },
  { english: 'open', turkish: 'açmak', level: 2 },
  { english: 'close', turkish: 'kapatmak', level: 2 },
  { english: 'begin', turkish: 'başlamak', level: 2 },
  { english: 'finish', turkish: 'bitirmek', level: 2 },
  { english: 'change', turkish: 'değişmek/değiştirmek', level: 2 },
  { english: 'travel', turkish: 'seyahat', level: 2 },
  { english: 'holiday', turkish: 'tatil', level: 2 },
  { english: 'ticket', turkish: 'bilet', level: 2 },
  { english: 'weather', turkish: 'hava durumu', level: 2 },
  { english: 'cloud', turkish: 'bulut', level: 2 },
  { english: 'storm', turkish: 'fırtına', level: 2 },
  { english: 'thunder', turkish: 'gök gürültüsü', level: 2 },
  { english: 'lightning', turkish: 'şimşek', level: 2 },
  { english: 'temperature', turkish: 'sıcaklık', level: 2 },
  { english: 'science', turkish: 'bilim', level: 2 },
  { english: 'history', turkish: 'tarih', level: 2 },
  { english: 'geography', turkish: 'coğrafya', level: 2 },
  { english: 'language', turkish: 'dil', level: 2 },
  { english: 'culture', turkish: 'kültür', level: 2 },
  { english: 'art', turkish: 'sanat', level: 2 },
  { english: 'film', turkish: 'film', level: 2 },
  { english: 'camera', turkish: 'kamera/fotoğraf makinesi', level: 2 },
  { english: 'newspaper', turkish: 'gazete', level: 2 },
  { english: 'magazine', turkish: 'dergi', level: 2 },
  { english: 'television', turkish: 'televizyon', level: 2 },
  { english: 'radio', turkish: 'radyo', level: 2 },
  { english: 'energy', turkish: 'enerji', level: 2 },
  { english: 'power', turkish: 'güç', level: 2 },
  { english: 'light', turkish: 'ışık', level: 2 },
  { english: 'sound', turkish: 'ses', level: 2 },
  { english: 'glass', turkish: 'cam/bardak', level: 2 },
  { english: 'bottle', turkish: 'şişe', level: 2 },
  { english: 'bag', turkish: 'çanta', level: 2 },
  { english: 'box', turkish: 'kutu', level: 2 },
  { english: 'key', turkish: 'anahtar', level: 2 },
  { english: 'watch', turkish: 'saat/izlemek', level: 2 },
  { english: 'clock', turkish: 'duvar saati', level: 2 },
  { english: 'knife', turkish: 'bıçak', level: 2 },
  { english: 'cup', turkish: 'fincan', level: 2 },
  { english: 'plate', turkish: 'tabak', level: 2 },
  { english: 'spoon', turkish: 'kaşık', level: 2 },
  { english: 'fork', turkish: 'çatal', level: 2 },
  { english: 'shirt', turkish: 'gömlek', level: 2 },
  { english: 'shoe', turkish: 'ayakkabı', level: 2 },
  { english: 'hat', turkish: 'şapka', level: 2 },
  { english: 'coat', turkish: 'palto', level: 2 },
  { english: 'dress', turkish: 'elbise', level: 2 },
  { english: 'pocket', turkish: 'cep', level: 2 },
  { english: 'mirror', turkish: 'ayna', level: 2 },
  { english: 'soap', turkish: 'sabun', level: 2 },
  { english: 'medicine', turkish: 'ilaç', level: 2 },
  { english: 'blood', turkish: 'kan', level: 2 },
  { english: 'pain', turkish: 'ağrı/acı', level: 2 },
  { english: 'strong', turkish: 'güçlü', level: 2 },
  { english: 'weak', turkish: 'zayıf', level: 2 },
  { english: 'heavy', turkish: 'ağır', level: 2 },
  { english: 'light', turkish: 'hafif/aydınlık', level: 2 },
  { english: 'deep', turkish: 'derin', level: 2 },
  { english: 'wide', turkish: 'geniş', level: 2 },
  { english: 'narrow', turkish: 'dar', level: 2 },
  { english: 'rich', turkish: 'zengin', level: 2 },
  { english: 'poor', turkish: 'fakir', level: 2 },
  { english: 'busy', turkish: 'meşgul', level: 2 },
  { english: 'free', turkish: 'özgür/ücretsiz', level: 2 },
  { english: 'safe', turkish: 'güvenli', level: 2 },
  { english: 'difficult', turkish: 'zor', level: 2 },
  { english: 'easy', turkish: 'kolay', level: 2 },
  { english: 'clean', turkish: 'temiz', level: 2 },
  { english: 'dirty', turkish: 'kirli', level: 2 },
  { english: 'beautiful', turkish: 'güzel', level: 2 },
  { english: 'ugly', turkish: 'çirkin', level: 2 },
  { english: 'right', turkish: 'doğru/sağ', level: 2 },
  { english: 'wrong', turkish: 'yanlış', level: 2 },
  { english: 'true', turkish: 'doğru/gerçek', level: 2 },
  { english: 'false', turkish: 'yanlış/sahte', level: 2 },
  { english: 'same', turkish: 'aynı', level: 2 },
  { english: 'different', turkish: 'farklı', level: 2 },
  { english: 'important', turkish: 'önemli', level: 2 },
  { english: 'interesting', turkish: 'ilginç', level: 2 },
  { english: 'serious', turkish: 'ciddi', level: 2 },
  { english: 'funny', turkish: 'komik', level: 2 },
  { english: 'angry', turkish: 'kızgın', level: 2 },
  { english: 'tired', turkish: 'yorgun', level: 2 },
  { english: 'hungry', turkish: 'aç', level: 2 },
  { english: 'thirsty', turkish: 'susuz/susamış', level: 2 },
  { english: 'ready', turkish: 'hazır', level: 2 },
  { english: 'perfect', turkish: 'mükemmel', level: 2 },
  // Seviye 3 — İleri düzey kelimeler
  { english: 'achievement', turkish: 'başarı', level: 3 },
  { english: 'adventure', turkish: 'macera', level: 3 },
  { english: 'agreement', turkish: 'anlaşma', level: 3 },
  { english: 'ambition', turkish: 'hırs/hedef', level: 3 },
  { english: 'ancient', turkish: 'antik/kadim', level: 3 },
  { english: 'anxious', turkish: 'endişeli', level: 3 },
  { english: 'apparent', turkish: 'görünür/belirgin', level: 3 },
  { english: 'approach', turkish: 'yaklaşım', level: 3 },
  { english: 'atmosphere', turkish: 'atmosfer', level: 3 },
  { english: 'attitude', turkish: 'tutum/davranış', level: 3 },
  { english: 'authority', turkish: 'otorite/yetki', level: 3 },
  { english: 'behavior', turkish: 'davranış', level: 3 },
  { english: 'benefit', turkish: 'fayda/kazanım', level: 3 },
  { english: 'campaign', turkish: 'kampanya', level: 3 },
  { english: 'capable', turkish: 'yetenekli/muktedir', level: 3 },
  { english: 'career', turkish: 'kariyer', level: 3 },
  { english: 'challenge', turkish: 'meydan okuma/zorluk', level: 3 },
  { english: 'character', turkish: 'karakter', level: 3 },
  { english: 'communicate', turkish: 'iletişim kurmak', level: 3 },
  { english: 'community', turkish: 'topluluk', level: 3 },
  { english: 'compare', turkish: 'karşılaştırmak', level: 3 },
  { english: 'compete', turkish: 'yarışmak/rekabet etmek', level: 3 },
  { english: 'confident', turkish: 'kendinden emin', level: 3 },
  { english: 'consequence', turkish: 'sonuç/etki', level: 3 },
  { english: 'consider', turkish: 'dikkate almak', level: 3 },
  { english: 'creative', turkish: 'yaratıcı', level: 3 },
  { english: 'curious', turkish: 'meraklı', level: 3 },
  { english: 'damage', turkish: 'hasar/zarar', level: 3 },
  { english: 'decision', turkish: 'karar', level: 3 },
  { english: 'democracy', turkish: 'demokrasi', level: 3 },
  { english: 'describe', turkish: 'tanımlamak/betimlemek', level: 3 },
  { english: 'develop', turkish: 'geliştirmek', level: 3 },
  { english: 'discover', turkish: 'keşfetmek', level: 3 },
  { english: 'discuss', turkish: 'tartışmak', level: 3 },
  { english: 'education', turkish: 'eğitim', level: 3 },
  { english: 'environment', turkish: 'çevre/ortam', level: 3 },
  { english: 'equality', turkish: 'eşitlik', level: 3 },
  { english: 'evidence', turkish: 'kanıt/delil', level: 3 },
  { english: 'evolution', turkish: 'evrim/gelişim', level: 3 },
  { english: 'experience', turkish: 'deneyim', level: 3 },
  { english: 'experiment', turkish: 'deney', level: 3 },
  { english: 'explain', turkish: 'açıklamak', level: 3 },
  { english: 'explore', turkish: 'keşfetmek/araştırmak', level: 3 },
  { english: 'failure', turkish: 'başarısızlık', level: 3 },
  { english: 'freedom', turkish: 'özgürlük', level: 3 },
  { english: 'generation', turkish: 'nesil/kuşak', level: 3 },
  { english: 'government', turkish: 'hükümet', level: 3 },
  { english: 'grateful', turkish: 'minnettar', level: 3 },
  { english: 'honest', turkish: 'dürüst', level: 3 },
  { english: 'imagine', turkish: 'hayal etmek', level: 3 },
  { english: 'include', turkish: 'dahil etmek', level: 3 },
  { english: 'independent', turkish: 'bağımsız', level: 3 },
  { english: 'industry', turkish: 'endüstri/sanayi', level: 3 },
  { english: 'influence', turkish: 'etki/nüfuz', level: 3 },
  { english: 'ingredient', turkish: 'malzeme/içerik', level: 3 },
  { english: 'innovation', turkish: 'yenilik/inovasyon', level: 3 },
  { english: 'intelligent', turkish: 'zeki/akıllı', level: 3 },
  { english: 'justice', turkish: 'adalet', level: 3 },
  { english: 'knowledge', turkish: 'bilgi/bilgi birikimi', level: 3 },
  { english: 'leadership', turkish: 'liderlik', level: 3 },
  { english: 'liberty', turkish: 'özgürlük/hürriyet', level: 3 },
  { english: 'majority', turkish: 'çoğunluk', level: 3 },
  { english: 'manage', turkish: 'yönetmek', level: 3 },
  { english: 'memory', turkish: 'bellek/hafıza', level: 3 },
  { english: 'minority', turkish: 'azınlık', level: 3 },
  { english: 'mysterious', turkish: 'gizemli', level: 3 },
  { english: 'necessary', turkish: 'gerekli/zorunlu', level: 3 },
  { english: 'negotiate', turkish: 'müzakere etmek', level: 3 },
  { english: 'observation', turkish: 'gözlem', level: 3 },
  { english: 'opinion', turkish: 'görüş/fikir', level: 3 },
  { english: 'opportunity', turkish: 'fırsat', level: 3 },
  { english: 'organize', turkish: 'düzenlemek', level: 3 },
  { english: 'patient', turkish: 'sabırlı/hasta', level: 3 },
  { english: 'pattern', turkish: 'örüntü/desen', level: 3 },
  { english: 'personal', turkish: 'kişisel', level: 3 },
  { english: 'philosophy', turkish: 'felsefe', level: 3 },
  { english: 'population', turkish: 'nüfus', level: 3 },
  { english: 'poverty', turkish: 'yoksulluk', level: 3 },
  { english: 'prevent', turkish: 'engellemek/önlemek', level: 3 },
  { english: 'privilege', turkish: 'ayrıcalık', level: 3 },
  { english: 'process', turkish: 'süreç/işlem', level: 3 },
  { english: 'produce', turkish: 'üretmek', level: 3 },
  { english: 'progress', turkish: 'ilerleme', level: 3 },
  { english: 'protect', turkish: 'korumak', level: 3 },
  { english: 'psychology', turkish: 'psikoloji', level: 3 },
  { english: 'purpose', turkish: 'amaç/hedef', level: 3 },
  { english: 'recognize', turkish: 'tanımak/fark etmek', level: 3 },
  { english: 'recommend', turkish: 'tavsiye etmek', level: 3 },
  { english: 'relationship', turkish: 'ilişki', level: 3 },
  { english: 'remarkable', turkish: 'dikkat çekici/olağanüstü', level: 3 },
  { english: 'represent', turkish: 'temsil etmek', level: 3 },
  { english: 'research', turkish: 'araştırma', level: 3 },
  { english: 'respect', turkish: 'saygı', level: 3 },
  { english: 'responsibility', turkish: 'sorumluluk', level: 3 },
  { english: 'revolution', turkish: 'devrim', level: 3 },
  { english: 'sacrifice', turkish: 'fedakarlık/kurban', level: 3 },
  { english: 'society', turkish: 'toplum', level: 3 },
  { english: 'solution', turkish: 'çözüm', level: 3 },
  { english: 'strategy', turkish: 'strateji', level: 3 },
  { english: 'struggle', turkish: 'mücadele', level: 3 },
  { english: 'success', turkish: 'başarı', level: 3 },
  { english: 'support', turkish: 'destek', level: 3 },
  { english: 'survive', turkish: 'hayatta kalmak', level: 3 },
  { english: 'technology', turkish: 'teknoloji', level: 3 },
  { english: 'tradition', turkish: 'gelenek', level: 3 },
  { english: 'transform', turkish: 'dönüştürmek', level: 3 },
  { english: 'transparent', turkish: 'şeffaf', level: 3 },
  { english: 'treasure', turkish: 'hazine/değerli şey', level: 3 },
  { english: 'trust', turkish: 'güven', level: 3 },
  { english: 'unique', turkish: 'eşsiz/benzersiz', level: 3 },
  { english: 'universe', turkish: 'evren', level: 3 },
  { english: 'valuable', turkish: 'değerli', level: 3 },
  { english: 'violence', turkish: 'şiddet', level: 3 },
  { english: 'volunteer', turkish: 'gönüllü', level: 3 },
  { english: 'wisdom', turkish: 'bilgelik', level: 3 },
];

export function getRandomWords(count: number, level?: 1 | 2 | 3): EnglishWord[] {
  const pool = level ? ENGLISH_WORDS.filter((w) => w.level === level) : ENGLISH_WORDS;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getDistractors(correct: EnglishWord, allWords: EnglishWord[], count = 3): string[] {
  const sameLevel = allWords.filter((w) => w.english !== correct.english && w.level === correct.level);
  const others = allWords.filter((w) => w.english !== correct.english && w.level !== correct.level);
  const pool = [...sameLevel, ...others].sort(() => Math.random() - 0.5);
  return pool.slice(0, count).map((w) => w.turkish);
}
