export const WORD_HINTS: Record<string, string> = {
  // Doğa & Çevre
  ELMA: "Meyve türü — kırmızı, yeşil veya sarı renkli olabilir",
  ARMUT: "Yumuşak etli, tatlı bir meyve türü",
  KIRAZ: "Küçük, kırmızı ve çekirdekli bir meyve",
  ÜZÜM: "Salkım halinde yetişen küçük meyveler",
  ŞEFTALI: "Tüylü kabuklu, çekirdekli tatlı bir meyve",
  ÇILEK: "Kırmızı, küçük ve aromalı bir meyve",
  KAVUN: "Sarı renkli, tatlı ve sulu bir meyve",
  KARPUZ: "İri, yeşil kabuklu, kırmızı etli yaz meyvesi",
  PORTAKAL: "C vitamini bakımından zengin, turuncu bir narenciye",
  LİMON: "Sarı renkli, ekşi narenciye meyvesi",
  MEYVE: "Yenilen bitki ürünü, çoğunlukla tatlı ve sulu",
  SEBZE: "Yenilen bitki kısımları, genellikle pişirilerek tüketilir",
  DOMATES: "Kırmızı renkli, aslında meyve olan sebze",
  SALATALIK: "Yeşil, uzun ve serin tadıyla bilinen sebze",
  SOĞAN: "Keskin kokulu, mutfakta yaygın kullanılan sebze",
  SARMIMSAK: "Güçlü kokulu, küçük dişlerden oluşan bitki",
  HAVUÇ: "Turuncu renkli, A vitamini bakımından zengin sebze",
  PATATES: "Toprak altında yetişen, nişastalı sebze",
  PATLICAN: "Mor renkli, uzun ve parlak yüzeyli sebze",
  BİBER: "Acı veya tatlı olabilen, renkli bir sebze",
  MARUL: "Yeşil yapraklı, salatalarda kullanılan sebze",
  ISPANAK: "Demir bakımından zengin, yeşil yapraklı sebze",
  FASULYE: "Baklagil türü, protein kaynağı sebze",
  MERCİMEK: "Protein bakımından zengin, yuvarlak baklagil",
  NOHUT: "Yuvarlak, sarımsı renkli baklagil",
  BUĞDAY: "Ekmek ve un yapımında kullanılan tahıl",
  PİRİNÇ: "Asya mutfağının temeli olan beyaz tahıl",
  MISI: "Sarı renkli, büyük taneli tahıl bitkisi",
  ARPA: "Bira ve hayvan yemi yapımında kullanılan tahıl",

  // Hayvanlar
  KEDI: "Evcil, miyav diyen, tüylü hayvan",
  KÖPEK: "İnsanın en sadık evcil hayvanı",
  AT: "Binme ve yük taşıma amacıyla kullanılan hayvan",
  İNEK: "Süt veren, çiftlikte yetiştirilen iri hayvan",
  KOYUN: "Yün veren, meleyen çiftlik hayvanı",
  KEÇİ: "Dağlık arazilerde yaşayan, süt veren hayvan",
  TAVUK: "Yumurta veren, kanatları olup uçamayan kuş",
  HORoz: "Sabah öten, ibikli erkek tavuk",
  ÖRDEK: "Suda yüzebilen, vak vak diyen kuş",
  KAZ: "Büyük ve beyaz, gagalı su kuşu",
  ASLAN: "Afrikada yaşayan, ormanların kralı olan yırtıcı",
  KAPLAN: "Çizgili tüylü, güçlü yırtıcı hayvan",
  FİL: "Dünyanın en büyük kara hayvanı, hortumlu",
  ZÜRAFa: "Boynu çok uzun, Afrika'nın yüksek hayvanı",
  ZEBRA: "Siyah-beyaz çizgili, at benzeri hayvan",
  MAYMUN: "İnsana benzeyen, ağaçlarda yaşayan memeli",
  BALINA: "Denizde yaşayan, memeli olan en büyük canlı",
  YUNUS: "Zeki ve sosyal deniz memelisi",
  KÖPEKBALIGI: "Okyanusun en güçlü avcı balığı",
  TIMSAH: "Sürüngen sınıfından, suda ve karada yaşayan",
  YILAN: "Bacaksız sürüngen, zehirli olabilir",
  KAPLUMBAĞA: "Kabuğu olan, yavaş hareket eden sürüngen",
  KARTAL: "Geniş kanatlı, keskin görüşlü yırtıcı kuş",
  BAYKUŞ: "Gece aktif olan, bilgeliğin simgesi kuş",
  PAPAĞAN: "İnsan sesini taklit edebilen renkli kuş",
  KELEBEK: "Renkli kanatlı, çiçekten çiçeğe konup uçan böcek",
  ARI: "Bal yapan, sokan, sürü halinde yaşayan böcek",
  SİNEK: "Isırıp rahatsız eden küçük uçan böcek",
  KARINCA: "Topluluk halinde yaşayan, güçlü küçük böcek",

  // Doğa & Coğrafya
  MASA: "Üzerine eşya konulan, bacaklı mobilya",
  SANDALYE: "Üzerine oturulan, sırtlıklı mobilya",
  KALE: "Tarihi savunma yapısı veya futbol kalesi",
  ARABA: "Motorlu, tekerlekli kara taşıtı",
  KALEM: "Yazı yazmak için kullanılan araç",
  BALIK: "Suda solungaçla nefes alan omurgalı",
  DENİZ: "Okyanusun bir parçası olan tuzlu su kitlesi",
  KİTAP: "Sayfaları bir arada, yazılı eser",
  OKUL: "Öğrencilerin eğitim gördüğü kurum",
  BULUT: "Gökyüzünde su buharı birikerek oluşan beyaz kütle",
  GÜNEŞ: "Dünyamıza ışık ve ısı veren yıldız",
  YILDIZ: "Geceleri parlayan uzak gök cismi",
  TOPRAK: "Bitkilerin yetiştiği yer kabuğunun üst katmanı",
  ORMAN: "Ağaçların yoğun olduğu geniş alan",
  ÇİÇEK: "Bitkinin üreme organı, renkli ve güzel",
  DAĞ: "Yerden yükselen doğal kara kütlesi",
  TEPe: "Dağdan daha alçak, yuvarlak yükseklik",
  IRMAK: "Kaynaktan denize akan büyük su yolu",
  NEHİR: "Büyük ve uzun akan tatlı su yolu",
  GÖLET: "Küçük, durgun tatlı su birikintisi",
  GÖL: "Kara ile çevrili büyük su birikintisi",
  ÇOBAN: "Koyun ve keçi güden kişi",
  ADA: "Etrafı su ile çevrili kara parçası",
  YANARDAĞ: "İçinden lav fışkıran dağ türü",
  ÇÖLLÜK: "Yağışın çok az, bitki örtüsünün seyrek olduğu alan",
  ÇÖL: "Çok sıcak ve kurak, kum ya da taşlık alan",
  BATAKLK: "Su ile doymuş, yumuşak zemin",
  BUZUL: "Uzun süre birikmiş sıkışmış kar ve buz kütlesi",
  KAYALIK: "Büyük taş kütlelerinden oluşan alan",

  // İnsan vücudu & Sağlık
  KALP: "Kanı vücuda pompalayan organ",
  BEYİN: "Düşünme ve sinir sistemini yöneten organ",
  AKCİĞER: "Solunumu sağlayan, çift kanatlı organ",
  MİDE: "Yiyeceklerin sindirildiği organ",
  KİBİR: "Kendini başkalarından üstün görme hali",
  KAN: "Damarlarda dolaşan kırmızı sıvı",
  KEMIK: "Vücudu destekleyen sert yapı",
  BAĞIŞIKLIK: "Hastalıklara karşı vücudun savunma sistemi",
  HÜCRE: "Canlıların en küçük yapı birimi",
  ATEŞ: "Vücut sıcaklığının normalin üzerine çıkması",
  İLAÇ: "Hastalıkları tedavi etmek için kullanılan madde",
  DOKTOR: "Hastaları teşhis ve tedavi eden sağlık uzmanı",
  HEMŞİRE: "Hastalara bakım veren sağlık çalışanı",
  HASTANE: "Hastaların muayene ve tedavi edildiği kurum",
  AMELİYAT: "Hastalıkları tedavi için yapılan cerrahi müdahale",
  YARALANMA: "Doku bütünlüğünün bozulması, kırık veya kesik",
  AŞILANMA: "Bağışıklık kazandırmak için yapılan iğne",
  BESLENME: "Vücudun ihtiyacı olan besinleri alma süreci",
  EGZERSİZ: "Sağlık için yapılan düzenli fiziksel hareket",
  NEFES: "Akciğerlere hava alıp verme eylemi",

  // Şehir & Mimari
  BİNA: "İçinde yaşanılan veya çalışılan yapı",
  KÖPRÜ: "İki yakayı birbirine bağlayan yapı",
  TÜNEL: "Dağ veya zemin altından geçen geçit",
  CAMİ: "Müslümanların ibadet ettiği yapı",
  KİLİSE: "Hristiyanların ibadet ettiği yapı",
  OKULA: "Öğrencilerin eğitim gördüğü bina",
  HASTANESI: "Hastaların tedavi edildiği büyük bina",
  KÜTÜPHANE: "Kitapların toplandığı ve ödünç verildiği yer",
  MÜZE: "Tarihi eserlerin sergilendiği kurum",
  PARK: "Halkın yararlanması için düzenlenmiş yeşil alan",
  BAHÇE: "Çiçek ve bitki yetiştirilen alan",
  MEZARLIK: "Ölülerin defnedildiği alan",
  PAZAR: "Satıcıların ürünlerini sergilediği açık alan",
  ÇARŞI: "Dükkanların bir arada olduğu alışveriş yeri",
  MİNARE: "Caminin yüksek kulesi, ezan okunur",
  SARAY: "Hükümdarların yaşadığı büyük ve görkemli bina",
  KALE2: "Duvarlarla çevrili tarihi savunma yapısı",
  KÖPRÜ2: "Dere veya nehir üzerindeki geçit yapısı",
  YURT: "Öğrencilerin kaldığı konaklama yeri",

  // Meslekler
  ÖĞRETMEN: "Öğrencilere bilgi ve beceri kazandıran kişi",
  MÜHENDİS: "Teknik projeleri tasarlayıp uygulayan uzman",
  MİMAR: "Bina ve yapıları tasarlayan uzman",
  AVUKAT: "Hukuki konularda danışmanlık yapan uzman",
  HÂKİM: "Mahkemede karar veren yetkili kişi",
  SAVCISI: "Suçluları mahkemede yargılayan hukuk uzmanı",
  ECZACI: "İlaç hazırlayan ve satan sağlık uzmanı",
  DİŞÇİ: "Diş sağlığıyla ilgilenen doktor",
  VETERİNER: "Hayvanları tedavi eden doktor",
  POLİS: "Kamu güvenliğini sağlayan görevli",
  ASKER: "Ülkeyi savunan silahlı kuvvet mensubu",
  İTFAİYECİ: "Yangınları söndüren ve kurtarma yapan görevli",
  PILOT: "Uçak kullanan, hava taşımacılığı uzmanı",
  KAPTAN: "Gemi veya uçağı yöneten sorumlu kişi",
  ŞEF: "Mutfakta yemek yapan uzman aşçı",
  GARSON: "Restoranda müşterilere hizmet eden kişi",
  KASIYER: "Alışveriş yerinde ödeme alan kişi",
  MUHASEBECİ: "Hesap ve mali işleri düzenleyen uzman",
  PROGRAMCI: "Bilgisayar programları yazan uzman",
  TASARIMCI: "Görsel içerik ve ürün tasarlayan uzman",

  // Duygular & Psikoloji
  MUTLULUK: "İyi hissettiren olumlu duygu durumu",
  ÜZÜNTÜ: "Hüzün ve keder hissi",
  KORKU: "Tehlike karşısında hissedilen tedirginlik",
  ÖFKE: "Sinirlenme, kızgınlık hali",
  SEVGİ: "Birisine derin bağlılık ve sıcaklık hissi",
  NEFRet: "Birinden çok hoşlanmama, iğrenme hissi",
  MERAK: "Bilinmeyen şeyleri öğrenme isteği",
  HEYECAN: "Olumlu veya olumsuz yoğun duygu hali",
  UMUT: "İyi bir şey olacağına duyulan inanç",
  HAYAL: "Gerçek olmayan olayları zihinde canlandırma",
  YALNIZLIK: "Tek başına olma veya hissetme durumu",
  GURur: "Kendini veya başkasını beğenme duygusu",
  UTANÇ: "Yaptığı bir şeyden dolayı kendini kötü hissetme",
  ŞÜKRAN: "Alınan iyilikler için duyulan minnettarlık",
  KISKANÇLIK: "Başkasının sahip olduğunu isteme duygusu",
  SABIR: "Bekleyip katlanabilme yeteneği",
  CESARet: "Korku karşısında doğru yapmayı seçebilme",
  VİCDAN: "Doğru ve yanlışı ayırt eden iç ses",
  EMPATI: "Başkasının duygularını anlayabilme yeteneği",

  // Eğitim & Bilim
  MATEMATİK: "Sayı ve hesaplama bilimiyle ilgilenen bilim dalı",
  FİZİK: "Madde ve enerjiyi inceleyen temel bilim",
  KİMYA: "Maddenin yapısını ve değişimlerini inceleyen bilim",
  BİYOLOJİ: "Canlıları ve yaşam süreçlerini inceleyen bilim",
  TARİH: "Geçmişteki olayları inceleyen bilim dalı",
  COĞRAFYA: "Yeryüzünü ve insan-doğa ilişkisini inceleyen bilim",
  FELSEFE: "Var oluş, bilgi ve değerleri sorgulayan düşünce",
  PSİKOLOJİ: "İnsan davranışı ve zihin süreçlerini inceleyen bilim",
  SOSYOLOJİ: "Toplum ve sosyal ilişkileri inceleyen bilim",
  EKONOMİ: "Üretim, dağıtım ve tüketimi inceleyen bilim",
  DENEY: "Bir hipotezi test etmek için yapılan gözlem",
  HİPOTEZ: "Kanıtlanmayı bekleyen bilimsel varsayım",
  TEORİ: "Geniş çapta kabul görmüş bilimsel açıklama",
  FORMÜL: "Matematiksel veya kimyasal ilişkiyi gösteren ifade",
  DENKLEM: "İki tarafı eşit olan matematiksel ifade",
  GEOMETRİ: "Şekil, boyut ve uzayı inceleyen matematik dalı",
  CEBIR: "Harfleri sayı yerine kullanan matematik dalı",
  İSTATİSTİK: "Veri toplama ve analiz bilimiyle ilgilenen alan",
  ATOM: "Maddenin en küçük yapı birimi",
  MOLEKÜL: "İki veya daha fazla atomun bir araya gelmesi",

  // Teknoloji & İletişim
  BİLGİSAYAR: "Veri işleyen elektronik cihaz",
  TELEFON: "Sesli veya yazılı iletişim sağlayan cihaz",
  İNTERNET: "Milyonlarca bilgisayarı birbirine bağlayan ağ",
  YAZILIM: "Bilgisayarı çalıştıran programlar bütünü",
  DONANIM: "Bilgisayarın fiziksel parçaları",
  VERİ: "İşlenmek üzere toplanan bilgi ve semboller",
  AĞBILGISAYAR: "Birbirine bağlı bilgisayar sistemi",
  UYGULAMA: "Belirli bir işlevi yerine getiren yazılım",
  ŞİFRE: "Kimlik doğrulama için kullanılan gizli kod",
  VİRÜS: "Bilgisayar sistemlerine zarar veren kötü yazılım",
  KAMERA: "Fotoğraf veya video çekmek için kullanılan cihaz",
  EKRAN: "Görüntülerin gösterildiği yüzey",
  KLAVYE: "Bilgisayara veri girmek için kullanılan gereç",
  FARE: "Bilgisayarda imleci hareket ettiren aygıt",
  YAZICI: "Dijital belgeleri kağıda basan cihaz",
  BELLEK: "Bilgilerin depolandığı hafıza birimi",
  İŞLEMCİ: "Bilgisayarın hesaplama yapan ana birimi",
  PIL: "Elektronik cihazlara enerji veren kaynak",
  KABLOSUZ: "Tel kullanmadan iletişim sağlayan sistem",
  BLUETOOTH: "Kısa mesafeli kablosuz veri aktarım teknolojisi",
};

export function getWordHint(word: string): string | null {
  return WORD_HINTS[word.toUpperCase()] ?? null;
}
